# Generated by Django 6.0.2 on 2026-06-24 17:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True)),
                ('condicion', models.CharField(choices=[('Riego', 'Riego'), ('Temporal', 'Temporal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hibrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatoClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dco', models.IntegerField(blank=True, null=True)),
                ('pp_anual', models.FloatField(blank=True, null=True)),
                ('pp_co', models.FloatField(blank=True, null=True)),
                ('tm_anual', models.FloatField(blank=True, null=True)),
                ('tmax_anual', models.FloatField(blank=True, null=True)),
                ('tmin_anual', models.FloatField(blank=True, null=True)),
                ('tm_co', models.FloatField(blank=True, null=True)),
                ('tmax_co', models.FloatField(blank=True, null=True)),
                ('tmin_co', models.FloatField(blank=True, null=True)),
                ('uca_co', models.FloatField(blank=True, null=True)),
                ('horas_calor_30', models.FloatField(blank=True, null=True)),
                ('horas_frio_5', models.FloatField(blank=True, null=True)),
                ('ghi', models.FloatField(blank=True, null=True)),
                ('ss', models.FloatField(blank=True, null=True)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clima', to='api.ciclo')),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='hibrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='api.hibrido'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodologia', models.CharField(blank=True, choices=[('Química Húmeda', 'Química Húmeda'), ('NIRS', 'NIRS')], max_length=50, null=True)),
                ('pem', models.FloatField(blank=True, null=True)),
                ('pff', models.FloatField(blank=True, null=True)),
                ('dff', models.FloatField(blank=True, null=True)),
                ('ucaff', models.FloatField(blank=True, null=True)),
                ('npc', models.FloatField(blank=True, null=True)),
                ('ppc', models.FloatField(blank=True, null=True)),
                ('rmf', models.FloatField(blank=True, null=True)),
                ('ms', models.FloatField(blank=True, null=True)),
                ('cen', models.FloatField(blank=True, null=True)),
                ('gc', models.FloatField(blank=True, null=True)),
                ('pc', models.FloatField(blank=True, null=True)),
                ('fdn', models.FloatField(blank=True, null=True)),
                ('cnf', models.FloatField(blank=True, null=True)),
                ('rms', models.FloatField(blank=True, null=True)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio', to='api.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud_norte_dms', models.CharField(blank=True, max_length=50, null=True)),
                ('longitud_oeste_dms', models.CharField(blank=True, max_length=50, null=True)),
                ('latitud_gps', models.FloatField(help_text='Coordenada Y')),
                ('longitud_gps', models.FloatField(help_text='Coordenada X')),
                ('altitud', models.FloatField(blank=True, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terrenos', to='api.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='api.terreno'),
        ),
        migrations.CreateModel(
            name='UsuarioCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('SADMIN', 'SADMIN'), ('JEFE', 'JEFE'), ('INVESTIGADOR', 'INVESTIGADOR')], default='INVESTIGADOR', max_length=20)),
                ('provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('es_investigador', models.BooleanField(default=False)),
                ('institucion', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'SADMIN')), fields=('role',), name='unique_sadmin_user')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
