# Generated by Codex on 2026-05-07

import os
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.hashers import make_password


def normalize_existing_users(apps, schema_editor):
    User = apps.get_model('api', 'UsuarioCustom')
    for user in User.objects.all():
        changed = False
        if not user.email:
            user.email = user.username
            changed = True
        user.email = user.email.lower().strip()
        if not user.username:
            user.username = user.email
            changed = True
        if getattr(user, 'es_investigador', False):
            user.role = 'INVESTIGADOR'
            changed = True
        if changed:
            user.save()


def create_initial_sadmin(apps, schema_editor):
    User = apps.get_model('api', 'UsuarioCustom')
    email = os.environ.get('SADMIN_EMAIL', 'sadmin@cropanalytics.local').lower().strip()
    password = os.environ.get('SADMIN_PASSWORD', 'CropAnalyticsSadmin123!')
    name = os.environ.get('SADMIN_NAME', 'Super Administrador')

    user = User.objects.filter(role='SADMIN').first() or User.objects.filter(email=email).first()
    if user is None:
        user = User(username=email, email=email)
    user.username = user.username or email
    user.email = email
    user.first_name = name
    user.role = 'SADMIN'
    user.provider = 'local'
    user.is_active = True
    user.is_staff = True
    user.is_superuser = True
    user.es_investigador = False
    user.password = make_password(password)
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='role',
            field=models.CharField(choices=[('SADMIN', 'SADMIN'), ('JEFE', 'JEFE'), ('INVESTIGADOR', 'INVESTIGADOR')], default='INVESTIGADOR', max_length=20),
        ),
        migrations.RunPython(normalize_existing_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usuariocustom',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='usuariocustom',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SADMIN')), fields=('role',), name='unique_sadmin_user'),
        ),
        migrations.RunPython(create_initial_sadmin, migrations.RunPython.noop),
    ]
