# Generated by Django 6.0.2 on 2026-10-07 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_soil_moisture_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='investigador', max_length=30, unique=True)),
                ('borrador', models.JSONField(default=list)),
                ('publicados', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigador_nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('parcela', models.CharField(max_length=150)),
                ('ciclo', models.CharField(choices=[('Riego', 'Riego'), ('Temporal', 'Temporal')], max_length=20)),
                ('datos', models.JSONField(default=dict)),
                ('version_config', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hibrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='api.hibrido')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='api.municipio')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
